routes:
  /:
    template: home
    data: page.home

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    data: page.blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
